name: spring rdf migration CI

on:
  push:
  pull_request:

jobs:
  buildDeploy:
    name: Build-Deploy
    runs-on: ubuntu-latest

    env:
      JDK_VERSION: 17

    steps:
      - uses: actions/checkout@v2

      # (1) -> Prepare cache and Java
      - name: Cache ~/.m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ env.JDK_VERSION }}-maven-${{ hashFiles('**/pom.xml') }}

      # (2) -> Prepare Java
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          version: ${{ env.JDK_VERSION }}

      - name: Verify Maven and Java
        run: |
          mvn --version
      # (3) -> Test and build
      - name: Run tests
        run: |
          mvn --quiet test
      - name: Build package
        run: |
          mvn --quiet -B --fail-fast -DskipTests package
